# The reviewers configuration for the auto_request_review workflow
# See https://github.com/necojackarc/auto-request-review/tree/master?tab=readme-ov-file#reviewers-configuration
# for the spec

reviewers:
  groups:
    migration-owners:
      - qnkhuat
      - calherries

files:
  # migrations related files
  #'resources/migrations/**':
  #  - migration-owners
      #- team:core-backend-components
  'src/metabase/db/custom_migrations.clj':
    - team:core-backend-components
      #- migration-owners

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
    - WIP
  enable_group_assignment: false
